ML Bootcamp 2021 - Week 2: Assignment

- In this week you will learn more about the Pandas library and implement Logistic Regression
- The comments will have most of the instructiions
- Attempt the questions using only python/pandas as much as possible as it is a very in-demand skill right now and learning it will be beneficial
- Use the Titanic Training dataset for all questions unless specified to use Test dataset

In [2]:
#Import the necessary libraries here
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, LogisticRegression # The Machine Learnig Algorithms
from sklearn.metrics import classification_report, mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler # This can be used to scale your data
import matplotlib.pyplot as plt
import seaborn as sb
import math

## Q1. What is the most frequently occuring age for male and female? If more than one particular age occurs equal number of times, report the higher of the two

In [6]:
# Write your code below the comments in this cell
# Important
# Save your female age value in a variable called 'age_female'
# Save your male age value in a variable called 'age_male'

####Code Comes Here###

df = pd.read_csv("./train.csv")


two = df[['Sex', 'Age']]


female = two['Sex'] == 'female'
male = two['Sex'] == 'male'

print(female)

print(two[female]['Age'].mode())
print(two[male]['Age'].mode())
###Code Comes Here###

###Answers come here###

age_female = 24
age_male = 28

###Answers come here###

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888     True
889    False
890    False
Name: Sex, Length: 891, dtype: bool
0    24.0
dtype: float64
0    19.0
1    25.0
2    28.0
dtype: float64

## Q2. Convert the 'Sex' feature of the Train dataset into categorical feature. This question would require you to first read about categorical features and how they look before proceeding.

- Read about categorical data first: https://www.kdnuggets.com/2021/05/deal-with-categorical-data-machine-learning.html
- Create a new column called "Sex_Category"
- Use the lambda and apply function to perform this task

In [ ]:
# Write your code below the comments in this cell
# Important
# Finally your dataframe should have an additional column called "Sex_Category"
# This "Sex_Category" column should have the entry as 1 wherever the column "Sex" shows "female" and 0 wherever it shows "male"
# Do not remove the existing "Sex" column, instead create a new column based on this existing column
# I have already provided the code to create a new column for your dataframe called "df"
# Refer to the previous notebooks for reference

####Code Comes Here###

df.dropna(inplace=True)
df['Sex_Category'] = df['Sex'].apply(lambda x: 1 if x == 'female' else 0)


###Code Comes Here###

NameError: ignored

## Q3. Consider the "Age" and the "Fare" columns. These are known as Numerical features. Sometimes it is a good idea to scale these features(bring all the numerical features to one scale maybe between {0,1} or between {-1,1} so that the weights are not biased across the features

- Bring these two features to a common scale
- There are many techniques to do this and scikit-learn provides many built-in libraries. Try to explore them and see how you can apply them. You would need to import the appropriate libraries
- You can use anyone. Without using scikit-learn, the simplest scaler that you can implement manually is to make the mean 0 and standard deviation as 1
- In order to do this manual implementation all you need to do is take each value of "Age" and "Fare", subtract the mean(mean of full column) from each value and then divide that result by the standard devaition(standard deviation of full column)
- If you decide to use the manual process then take the mean of all values except the NULL/Missing values as otherwise you may get an error

In [ ]:
# Write your code below the comments in this cell
# Important
# Finally your dataframe should have two additional columns called "Age_Normalized" and "Fare_Normalized"
# Do not remove the existing "Age" or "Fare" column, instead create new columns based on these existing columns
# Refer to the previous notebooks for reference and also Q2 to understand how to add new columns to an existing dataframe
# Use the apply and lambda function to perform the calculations
# If you choose to use the scikit-learn libraries then make sure to import them first at the very top cell

from sklearn.preprocessing import MinMaxScaler

####Code Comes Here###

df['Age_Normalized'] = MinMaxScaler().fit_transform(np.array(df['Age']).reshape(-1, 1))
df['Fare_Normalized'] = MinMaxScaler().fit_transform(np.array(df['Fare']).reshape(-1, 1))
df['Fare_Normalized'] = MinMaxScaler().fit_transform(np.array(df['Fare']).reshape(-1, 1))


print(df)
###Code Comes Here###

     PassengerId  Survived  ...  Age_Normalized Fare_Normalized
1              2         1  ...        0.468892        0.139136
3              4         1  ...        0.430956        0.103644
6              7         0  ...        0.671219        0.101229
10            11         1  ...        0.038948        0.032596
11            12         1  ...        0.721801        0.051822
..           ...       ...  ...             ...             ...
871          872         1  ...        0.582701        0.102579
872          873         0  ...        0.405665        0.009759
879          880         1  ...        0.696510        0.162314
887          888         1  ...        0.228629        0.058556
889          890         1  ...        0.317147        0.058556

[183 rows x 15 columns]

## Q4. Implement the ****Logistic**** function in Python based on the formula provided in the slides. All you need is provided in the numpy module or math module. There is a mistake, the place where I mention "Logit" function in the slides it is actually called "Logistic" function and not Logit function

In [ ]:
# Write your code below the comments in this cell
# Important
# Define a function and name it "logistic_fn"
# Return the final result of the logistic function
# The equation of the logistic function is present in the slides
####Code Comes Here###

import math

def logistic_fn(x):
    return (1/(1 + math.e**-x))

###Code Comes Here###

#Verification
# logistic_fn(1) --> 0.7310585786300049

## Q5. Using the above newly generated features, "Age_Normalized", "Fare_Normalized", "Sex_Category" and ****any other feature of your choice****. Implement the Logistic Regression Function just as was described in the last class notebook

- Import the Logistic Regression Function from scikit-learn
- Select the appropriate features first from your dataframe
- Create appropriate variables called x_train, x_test, y_train, y_test using the splitting function showed before. Split the Training dataset itself into two parts: Training and Testing(also called Validation)
- Use all the features that you created now and REMEMBER, an ML model only accepts Numerical features. Now you will understand the importance of converting categorical data to numbers
- Then train/fit() your training data to the Logistic Regression Model and then test/predict() it on your test dataset
- ****The problem here is "Titanic Survival Prediction". From this name think about what is the output/label for this classification task. That single column will be your y_train/y_test. It was also accounced in class as well****

- Keep the "random_state" paramenter inside the Logistic Regression function as any number of your choice and and report that number when submitting the assignment so that I can recreate your results. That number can be any integer

- Print out the classification_report as shown during the class

In [ ]:



df['Pclass_Normalized'] = MinMaxScaler().fit_transform(np.array(df['Pclass']).reshape(-1, 1))

x_train, x_test, y_train, y_test = train_test_split(df[['Fare_Normalized','Sex_Category', "Age_Normalized", "Pclass_Normalized"]], df[['Survived']], test_size=0.1)

# //random state of 100
log_reg = LogisticRegression(class_weight={1:0.6,0:0.5, 0:0.4, 0:0.5}, C=0.7, random_state = 100)# Initializing the model
log_reg.fit(x_train, y_train)

pd.set_option("display.max_rows", None, "display.max_columns", None)
print(y_test)
predict = log_reg.predict(x_test)

print(classification_report(y_test,predict))

     Survived
867         0
796         1
742         1
599         1
647         1
3           1
305         1
872         0
54          0
230         1
445         1
701         1
318         1
498         0
710         1
183         1
583         0
434         0
369         1
              precision    recall  f1-score   support

           0       0.50      0.17      0.25         6
           1       0.71      0.92      0.80        13

    accuracy                           0.68        19
   macro avg       0.60      0.54      0.53        19
weighted avg       0.64      0.68      0.63        19

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)